### PR TITLE
Gatsby Agency Starter

### PR DESCRIPTION
**Pull request by gomandev**

### CODE REVIEW

**Comment by gomandev** [comment]
Hey @boris-becomes the gatsby starter is up.

**Comment by boris-becomes** [comment]
@gomandev 

- Home page portfolio swiper: missing items label below the covers
- Services page hero: Wrong subtitle
- All pages: Wrong meta tags used, such as title
- Console error: All links have <a> inside of <a>. Use Gatsby Link for internal pages, and regular <a> for external.

Everything else seems great! Thanks

**Comment by gomandev** [comment]
Hey @boris-becomes the fixes has been made. thank you for the review. :)

**Comment by boris-becomes** [comment]
Hey @gomandev 

The title from the browser tabs is missing on the Home and Legal pages, and there are still places where nested <a> tags are such as Home Portfolio items. Also, if you can fix the letter capitalization on the 2nd bullet point from my previous comment.

**Comment by gomandev** [comment]
@boris-becomes Apologies for the back and forth man.

**Comment by boris-becomes** [comment]
@gomandev It's ok, it happens :smile:

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
