### PR TITLE
feat: Added Job Board Starter

### PR DESCRIPTION
**Pull request by gomandev**
Hi @boris-becomes

### CODE REVIEW

**Comment by boris-becomes** [comment]
@gomandev  The issue with the graphql pointers was on our end and it's fixed. You have to update the package: `npm i -D gatsby-source-bcms@latest` so it's `"gatsby-source-bcms": "^3.0.4"`

**Comment by gomandev** [comment]
> @gomandev The issue with the graphql pointers was on our end and it's fixed. You have to update the package: `npm i -D gatsby-source-bcms@latest` so it's `"gatsby-source-bcms": "^3.0.4"`

@boris-becomes Thank you, the fixes has been made.

**Comment by boris-becomes** [comment]
@gomandev 

- Can we make the transition on dropdown and make the click outside close it?
- Autocomplete missing on the Home page on the Locations search field - compare with the live version when you start typing any available location
- Fix autocomplete for the Search field - autocomplete value is wrong ( try typing "Wa" for "Waitress" )
- Handle error state on Contact page fields on empty submit
- On the About Us page the content for the About Us section is missing
- Update the domain link on the PageWrapper.tsx component

**Comment by gomandev** [comment]
> @gomandev
> 
>     * Can we make the transition on dropdown and make the click outside close it?
> 
>     * Autocomplete missing on the Home page on the Locations search field - compare with the live version when you start typing any available location
> 
>     * Fix autocomplete for the Search field - autocomplete value is wrong ( try typing "Wa" for "Waitress" )
> 
>     * Handle error state on Contact page fields on empty submit
> 
>     * On the About Us page the content for the About Us section is missing
> 
>     * Update the domain link on the PageWrapper.tsx component

@boris-becomes The fixes has been made. apologies for the back and forth.

**Comment by boris-becomes** [comment]
@gomandev 

I still don't see autocomplete on the "Search" field on the Home page. If I type "wa" I'm expecting to get the "itress". And for the "Locations" field It works only if I start typing the location name from the start, but if I type "Tulun" I'm also expecting to get the autocomplete for the rest of the "Tulungagung".

Everything else is great!

**Comment by gomandev** [comment]
> @gomandev
> 
> I still don't see autocomplete on the "Search" field on the Home page. If I type "wa" I'm expecting to get the "itress". And for the "Locations" field It works only if I start typing the location name from the start, but if I type "Tulun" I'm also expecting to get the autocomplete for the rest of the "Tulungagung".
> 
> Everything else is great!

@boris-becomes My bad, the issue has been resolved.

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
