### PR TITLE
feature: gatsby recipe starter

### PR DESCRIPTION
**Pull request by siradji**

### CODE REVIEW

**Comment by siradji** [comment]
@boris-becomes thanks!

**Comment by boris-becomes** [comment]
@siradji 

- The src/templates folder is missing, so the local server can't be run because that folder is needed for the pages generated from the `gatsby-node.ts` file.

**Comment by boris-becomes** [comment]
@siradji 

 - Home page - recipes sections - arrow on the button is black and should be white ( green on hover )
 - Single recipe page - steps section - arrows on the navigation buttons should be grayed-out just like the text when on first/last slide
 - Home page - top section - search bar - when typing "pe" the autocomplete shows the rest of the recipe's name ( "ppers" ), but when pressing the tab button to select that name the "pe" part is appended to the whole name "peppers" and the result is "pepeppers" but should be just "peppers"
 - Favicon
 - Rename "Next" to "Gatsby" ins PageWrapper.tsx

**Comment by siradji** [comment]
@boris-becomes, i have made all icons to native elements + auto complete fix

**Comment by siradji** [comment]
@boris-becomes  Apologies for the back and forth

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
