### PR TITLE
feature(next-migration):  tastyyy starter

### PR DESCRIPTION
**Pull request by siradji**
Loom Demo 

https://www.loom.com/share/36af07c868dc404da93050c94d46e5e6

### CODE REVIEW

**Comment by siradji** [comment]
@boris-becomes ,  just hold on.  Let me push some commits. thanks

**Comment by siradji** [comment]
@boris-becomes  you can review now. Look forward to the a fast review like yesterday

**Comment by boris-becomes** [comment]
Hey @siradji 

Here are some things I found that should be fixed:

- `Footer nav` styles missing
- `/legal` page is breaking
- `Home Hero map`, missing show/hide transitions on mobile ( most likely all `fade` transitions missing )
- `Home Ambience` ( 1st grid item on desktop ) and `Home Daily Specials` ( last grid item on desktop ) should be smaller in height ( different aspect ratio which is applied by missing CSS )
- `About Us` page, missing images from the bottom section ( image-text, text-image, image-text )

**Comment by siradji** [comment]
@boris-becomes , apologies stashed commits. Give me a minute

**Comment by siradji** [comment]
Just a side note, do you experience server crash when you run the project locally?

**Comment by boris-becomes** [comment]
@siradji I don't. I only couldn't load the /legal page because something is broken around `seo` title... Do you have a screenshot of an error or something?

**Comment by siradji** [comment]
@boris-becomes , the docker container crashes. only happens when i include daily specials image and content. 


image

**Comment by boris-becomes** [comment]
Maybe @Bbanez can help with the error?

**Comment by siradji** [comment]
@boris-becomes , all fixes a pushed expect for `About Us page, missing images from the bottom section ( image-text, text-image, image-text )`. It appears to be an issue with the server crashing... Placeholder images work just fine but images from the CMS, won't show

**Comment by boris-becomes** [comment]
@siradji I noticed there are still no fade transitions ( mainly for the Home Hero map ). And for the image-text text-image section on the About page, class that is applied on the `<ContentManager>` should be applied on the first element inside that component ( which is a `<div>` ), and that will make it 50/50% in size and images will be visible... Can you fix that and I can approve the pull. Thanks!

**Comment by siradji** [comment]
@boris-becomes , thanks! Fingers crossed this should fix everything - transitions and the about page. Let me know what you think

**Comment by siradji** [comment]
Thanks @boris-becomes

**Review by boris-becomes — APPROVED** [review]

**Comment by siradji** [comment]
@boris-becomes , is there a problem> why this isn't in?

**Pull request merged**
