### PR TITLE
feature: ecommerce gatsby

### PR DESCRIPTION
**Pull request by siradji**

### CODE REVIEW

**Comment by boris-becomes** [comment]
Thanks @siradji 

I've noticed some issues:

- On the home page, on the section with 6 category cards there is always "( 3 Products )" text, but should show the real number of products for that category
- Also on the home page, at the bottom where the products are shown, there should be a default background behind the size items ( "M", "L", etc )
- Legal page can't be accessed
- On the shop page, a space is missing in between "3 Productsfound"
- On the shop page, when a filter is active, the "X" icon should be of different color by default in the list of all selected filters
- On the product page ( swimwear ), there is "0" shown below the price - I suppose from the conditional for the discount price
- Update the domain link on the PageWrapper component

**Comment by siradji** [comment]
@boris-becomes, thanks for the review. The PR was WIP. i didn't mark it as such. But all good, fixed the above and worked on other things as well

**Comment by boris-becomes** [comment]
Awesome @siradji 

One last thing I noticed is that when you click on a category card from the Home page, you are redirected to the Shop page, but the selected category is not checked in the filters which should happen. Other things are fixed

**Comment by siradji** [comment]
@boris-becomes, check now please

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
