### PR TITLE
Next.js Agency Starter

### PR DESCRIPTION
**Pull request by gomandev**

### CODE REVIEW

**Comment by siradji** [comment]
@boris-becomes, i think there is an issue on the nextjs BCMS plugin. Images can not be found. For reference, check below

```
ERROR] [4/22/2024, 1:05:29 PM] /node_modules/@becomes/purple-cheetah/rest/middleware/http-exception-handler.js:17:37 HTTP Exception Handler Middleware  >
cms_backend-1  | {
cms_backend-1  |   "status": 404,
cms_backend-1  |   "stack": [
cms_backend-1  |     "Error",
cms_backend-1  |     "    at Object.occurred (/app/node_modules/@becomes/purple-cheetah/rest/error.js:16:24)",
cms_backend-1  |     "    at getBinFile (/app/src/media/controller.ts:65:28)",
cms_backend-1  |     "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
cms_backend-1  |     "    at async Object.handler (/app/src/media/controller.ts:361:18)",
cms_backend-1  |     "    at async handler (/app/node_modules/@becomes/purple-cheetah/rest/controller/main.js:39:39)"
cms_backend-1  |   ],
cms_backend-1  |   "message": {
cms_backend-1  |     "code": "mda001",
cms_backend-1  |     "message": "Media with ID \"65f2b0aeaa3e85c757d40862\" does not exist."
cms_backend-1  |   }
cms_backend-1  | }
```

image

**Comment by boris-becomes** [comment]
Hey @siradji 

Images are not showing because the 'publicApiKeyId' is wrong - located in pages/_app.tsx. It should be '65f1725abe4bcfba284afdbe' ( copied from the Nuxt/Agency )

**Comment by siradji** [comment]
> Hey @siradji
> 
> Images are not showing because the 'publicApiKeyId' is wrong - located in pages/_app.tsx. It should be '65f1725abe4bcfba284afdbe' ( copied from the Nuxt/Agency )

Super! Thanks man

**Comment by boris-becomes** [comment]
Hey, thanks for your work @siradji  @gomandev! Here's a list of things I found that could be improved before we push the starter

- `@svgr/webpack` package missing from the devDependencies and can't run the project locally.
- `/services` page has the wrong subtitle in the hero section ( "Portfolio" => "Our services" )
- Footer component should always be at the bottom of the page, no matter the height of the screen - found issue on `/contact` page on mobile screen 
Screenshot from 2024-04-23 12-48-10
- Missing `Contact Us` button on the Home page's Hero section on mobile
- `og-head` composable is using the data from the CONference starter - remove composable if not being used, but make sure to have all meta/link tags ( e.g. canonical tag is missing ) from the composable as in Nuxt.
- Make sure all images have `alt` attribute with value - found 1 for the footer cut-off logo - check other places
- When working with SVGs and `filled` or `fontControlled` attributes make sure to pass true/false values as strings - warning in console if boolean is passed.
- Run lint and fix errors if any are present
- File formatting - Example _app.tsx has multiple empty lines which shouldn't be present, and upon saving the file they're removed because we have set up a formatter. So make sure all files are formatted accordingly
- Update README.md - copy from Nuxt - replace all "Nuxt" instances with "Next" ( links to integrations and official docs too - found at the bottom of the file )

**Comment by gomandev** [comment]
Hey @boris-becomes, the fixes has been made. thanks.

**Comment by boris-becomes** [comment]
Thanks @gomandev!

I still don't see the canonical meta tag, and I found "nuxt" mentioned in the README in 2 places - can you fix these, too?

**Comment by gomandev** [comment]
All are done @boris-becomes.

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
