### PR TITLE
feature: next migration personal starter

### PR DESCRIPTION
**Pull request by siradji**
Loom video demo [DEMO](https://www.loom.com/share/3ad490e306c94c70adf11bc67094a882)

### CODE REVIEW

**Comment by boris-becomes** [comment]
Hi @siradji Great job! I will list some minor things that I noticed are missing:

- favicon and other files from the `public` folder are not loaded
- Helvetica font is not loaded properly ( you can check text that has `font-Helvetica` class and it looks different from the Nuxt version )
- On the Contact page, if no inputs are filled and you click submit you should get an error state for each input ( red label - check Nuxt version )
- og:meta tags ended up being empty - og-head ( and probably error ) composable missing

**Comment by siradji** [comment]
Thanks @boris-becomes  please let's get this in today 🙏🏽🙏🏽🙏🏽. I will send the updates

**Comment by siradji** [comment]
@boris-becomes , changes are pushed

**Comment by siradji** [comment]
> Hi @siradji Great job! I will list some minor things that I noticed are missing:
> 
> * favicon and other files from the `public` folder are not loaded
> * Helvetica font is not loaded properly ( you can check text that has `font-Helvetica` class and it looks different from the Nuxt version )
> * On the Contact page, if no inputs are filled and you click submit you should get an error state for each input ( red label - check Nuxt version )
> * og:meta tags ended up being empty - og-head ( and probably error ) composable missing

for the fonts comment, i checked and both sites are using Helvetica. You can verify that in the broweser

**Comment by boris-becomes** [comment]
@siradji Oh I see it's looking good in Chrome, but for some reason Helvetica is not being applied in Firefox

**Comment by siradji** [comment]
hey @boris-becomes  my man,. Please look at this. 

https://www.loom.com/share/6ba8dcf2cd7f4a58908205f3764158a2

**Comment by boris-becomes** [comment]
@siradji Thanks for the video... I'll assume I have some browser settings that blocks my device from loading the font for me. Everything else is great. Thanks once again!

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
