### PR TITLE
Thc/gatsby coonference

### PR DESCRIPTION
**Pull request by gomandev**

### CODE REVIEW

**Comment by boris-becomes** [comment]
@gomandev Are you getting any kind of error when trying to run the `npm run dev` command? I can't start the local server because of one related to `building-schema`

**Comment by gomandev** [comment]
> @gomandev Are you getting any kind of error when trying to run the `npm run dev` command? I can't start the local server because of one related to `building-schema`

Yes, I think is related to schema, but i have a way around it: `exports.createSchemaCustomization = ({ actions }: any) => {
  const { createTypes } = actions;

  const typeDefs = `
    scalar number
    scalar Number 
  `
  createTypes(typeDefs)
}` inserting this in gatsby-node.ts.

**Comment by gomandev** [comment]
@siradji

**Comment by boris-becomes** [comment]
@gomandev 

- Inter font is not loaded
- Missing modal transition when clicked on the "Contact us" from the Header and "Legal page" from the Footer
- Missing arrow across the "About" title on the Home page

**Comment by gomandev** [comment]
@boris-becomes issues are resolved.

**Comment by boris-becomes** [comment]
@gomandev Can we also remove the personal folder from this pull request so that we merge just the conference?

**Comment by gomandev** [comment]
@boris-becomes the personal folder has been removed, thanks.

**Review by boris-becomes — APPROVED** [review]

**Comment by boris-becomes** [comment]
@gomandev We will need to resolve the conflicts before merging. Can you help with that? Also, please update the PageWrapper.tsx file ( Next => Gatsby, Flavour Fusion => CONference ) and favicon. Thanks!

**Comment by gomandev** [comment]
Sure! but for me to be able to resolve the conflict I would need an access.
Screenshot 2023-11-21 at 11-50-08 feat gatsby-personal-starter by gomandev · Pull Request #34 · bcms_starters

**Comment by boris-becomes** [comment]
@gomandev Okay, I'll play with the conflict then, you can take the rest

**Comment by gomandev** [comment]
@boris-becomes I don't think Conference starter have a favicon. I couldn't find it in both nuxt and nextjs and also the live version: https://conference-starter.thebcms.com/. But the other fixes are ready.

**Comment by boris-becomes** [comment]
@gomandev Sorry, that is right!

**Comment by boris-becomes** [comment]
@gomandev I've merged it manually because the conflict was very big. All is good now, thanks!

**Comment by gomandev** [comment]
@boris-becomes Apologies Man, thank you. :)

**Pull request closed without merging**
