### PR TITLE
feature(gatsby-migration): Gatsby restaurant starter

### PR DESCRIPTION
**Pull request by siradji**
[Loom Video Demo ](https://www.loom.com/share/35635cf631ff423db6757e5acb13e66c)

### CODE REVIEW

**Comment by siradji** [comment]
@boris-becomes

**Comment by boris-becomes** [comment]
@siradji 

- Missing the `${pageTitle} - Tastyyy` title
- Helvetica font is not being imported in any way
- Wrong favicon ( src/images )
- Arrow from the buttons is not visible
- Menu page is missing the title in the top section

**Comment by siradji** [comment]
@boris-becomes , the issue with arrow not  showing on buttons is due to lack of svg optimization, but i fixed it now. Please review the changes and let me know. Thanks

**Comment by boris-becomes** [comment]
@siradji Great!

Can you also rename "Next" to "Gatsby" in PageWrapper.tsx? And on the home page, the hero section, `Open 9AM-9PM` should be aligned differently and styled ( font-size ) as `Birmingham, St. 9`.

**Comment by siradji** [comment]
@boris-becomes  done. Please recheck

**Comment by boris-becomes** [comment]
@siradji I found something else in the meantime:

- Reservation page is missing the title at the top
- Home hero - This time "(Mon-Sat)" text is different-size and color

**Comment by siradji** [comment]
@boris-becomes, here you go

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
