### PR TITLE
feature(next-migration): podcast starter

### PR DESCRIPTION
**Pull request by siradji**
Loom Video with demo [LOOM DEMO](https://www.loom.com/share/c688584a02c5470f91480a5a10763ede)

### CODE REVIEW

**Comment by boris-becomes** [comment]
@siradji Great job on this one! 

Minor things to fix:

- Add the og-head composable so we get the description and other meta fields populated?
- Order tracks by date from newest to oldest
- Add smooth scroll when clicking on the `Episodes` nav item
- On the Home page, the title and description from the Hero section is repeated on the section below and should be different.

**Comment by siradji** [comment]
Thanks @boris-becomes   please let's get this in today 🙏🏽🙏🏽🙏🏽. I will send the updates

**Comment by siradji** [comment]
@boris-becomes , all issues and changes are worked on. Let me know your thoughts

**Comment by boris-becomes** [comment]
@siradji For some reason 3 episodes from the `Home hero` are showing the wrong images. Also, all episodes have `02:156` duration format, and the duration is wrong - "Optimizing Your Nutrition for Practice" should be `02:36` . Everything else looks good!

**Comment by siradji** [comment]
@boris-becomes , fixed! Thanks for spotting that. Too much regression but we are good to go now. 

image

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
