### PR TITLE
feature: gatsby podcast starter

### PR DESCRIPTION
**Pull request by siradji**

### CODE REVIEW

**Comment by boris-becomes** [comment]
@siradji 

- Every episode has 'N/A', but most of them should display the name of the guest and fallback to 'N/A' only if there are no guests.
- Add thumbnail image in the static folder

**Comment by siradji** [comment]
@boris-becomes, the issue with the guest has to do with the graphql as it is returning null. Not sure if the issue is from the CMS or the queries (very unlikely) will investigate further and let you kno re

**Comment by boris-becomes** [comment]
@siradji The issue is most-likely at our end. We are also investigating... This goes for the Job-board as well

**Comment by siradji** [comment]
okay, the PR will be a [WIP] 🚧  till investigation is done. By the way the thumbnail issue is fixed. Let me know how it goes on your side.

**Comment by boris-becomes** [comment]
@siradji The issue was on our end and it's fixed. You have to update the package: `npm i -D gatsby-source-bcms@latest` so it's `"gatsby-source-bcms": "^3.0.4"`

**Comment by siradji** [comment]
Thanks @boris-becomes , the guest section is now showing. Review the PR and let me know

**Comment by boris-becomes** [comment]
@siradji Great, but also on the home page, below each episodes' title and on the player
Screenshot

**Comment by siradji** [comment]
@boris-becomes , fixed.

**Review by boris-becomes — APPROVED** [review]

**Pull request merged**
